Fix note to be nice
pomkos/money_requesting pull request #28
Opened 2021-01-10 18:55 UTC by Geczy

2021-01-10 18:57 UTC, pomkos commented on apps/calculator.py
> +        statement = f'Waaasssuup {key}\nTotal '
not happening lmao

2021-01-10 18:58 UTC, pomkos requested changes

2021-01-10 18:58 UTC, pomkos commented on apps/calculator.py
> +        statement += f'.\n\nMade with ❤️ at payme.peti.work' # %0A creates a new line
This didn't work in url.

2021-01-10 20:02 UTC, pomkos commented on apps/calculator.py
> +        statement += f'''.
Why so many newlines

2021-01-10 20:11 UTC, Geczy commented on apps/calculator.py
> +        statement += f'''.
its more professional

2021-01-13 15:57 UTC, pomkos approved these changes

2021-01-13 15:57 UTC, merged